name: Deploy to EC2

# run on push main branch
on:
  push:
    branches:
      - main  

jobs:
  my_first_job:
    name: CI/CD job
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v5

      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          
      
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_KEY_EC2 }}" > private.key
          chmod 600 private.key
        
      
      - name: Run Ansible Playbook v2
        run: |
          ansible-playbook -i Ansible/inventory.ini Ansible/docker_setup.yml --extra-vars "ansible_host=${{ secrets.IP_HOST_EC2 }}" --extra-vars "ansible_ssh_private_key_file=private.key" 

      - name: Verify website is running
        run: |
          echo "Waiting 5 seconds for container to start..."
          sleep 5
          echo "Pinging the website's public IP..."
          curl --fail http://${{ secrets.IP_HOST_EC2 }}