name: Deploy to EC2

# run on push main branch
on:
  push:
    branches:
      - main  

jobs:
  terraform:
    name: "Job 1: Run Terraform"
    runs-on: ubuntu-latest

    outputs:
      instance_ip: ${{ steps.set_ip.outputs.ip_address }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PWD_ACCESS_KEY_AWS }}
          aws-region: eu-west-1 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve #do not stop waiting for "yes"
        working-directory: ./Terraform

      - name: Get Terraform IP and save it
        id: set_ip 
        run: |
          IP_FROM_TF=$(terraform output -raw instance_ip)
          echo "ip_address=$IP_FROM_TF" >> "$GITHUB_OUTPUT"
          echo "Instance provisioned at: $IP_FROM_TF"
        working-directory: ./Terraform


  ansible:
    name: "Job 2: Run Ansible"
    runs-on: ubuntu-latest
    needs: [terraform] # if no instance, will fail
    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v5

      
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          
      
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_KEY_EC2 }}" > private.key
          chmod 600 private.key
        
      
      - name: Run Ansible Playbook
        run: |
          ansible-playbook \
            --inventory "${{ needs.terraform.outputs.instance_ip }}," --private-key private.key --user ec2-user --ssh-extra-args "-o StrictHostKeyChecking=no" Ansible/docker_setup.yml
    
      - name: Verify website is running
        run: |
          echo "Waiting 5 seconds for container to start..."
          sleep 5
          echo "Pinging the website's public IP..."
          curl --fail http://${{ needs.terraform.outputs.instance_ip }}